# Generated by Django 3.2.5 on 2021-07-16 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Employee name')),
                ('phone', models.CharField(max_length=50, verbose_name='Employee phone')),
                ('email', models.CharField(max_length=50, verbose_name='Employee email')),
                ('address', models.CharField(max_length=50, verbose_name='Employee address')),
            ],
        ),
    ]
