# Generated by Django 3.2.5 on 2021-07-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandLord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='company_name')),
                ('subdomain', models.CharField(max_length=50, verbose_name='sub_domain')),
                ('db_name', models.CharField(max_length=70, verbose_name='database name')),
            ],
            options={
                'verbose_name': 'LandLord',
                'verbose_name_plural': 'LandLords',
                'db_table': 'landlords',
            },
        ),
    ]
